version: "3.0"
services:
  ytsync:
    image: ytdl:1.0.0
    container_name: ytsync
    restart: always
    environment:
      MONGODB_URI: "enter mongodb URI here"
      INTERVAL: 30
      ROOTDIR: "."
